name: Sync labels Across Team-Incube
# desc: workflow에 정의된 레포에 기본 라벨 추가

on:
  workflow_call:
      secrets:
        org_label_token:
          required: true

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Sync labels
        uses: EndBug/label-sync@v1
        with:
          token: ${{ secrets.org_label_token }}
          delete-other-labels: false
          source-repo: team-incube/.github
